const PRIVATE_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCkfX3EThKKoitMygzqDrTanPCEwpYV0Gj+WtWHQIDAQAB";
const SALT = 10;

const ACCESS_TOKEN_SECRET = '43o57tfn1p5wgl7a499ft5mw64c9qv';
const ACCESS_TOKEN_LIFE = '20m'; // 20 min

const REFRESH_TOKEN_SECRET = 'n8qw1sl4aa2b9mspgyu3ky46s4ei17';
const REFRESH_TOKEN_LIFE = '60d'; // 60 days

module.exports = {
  ACCESS_TOKEN_SECRET,
  ACCESS_TOKEN_LIFE,
  REFRESH_TOKEN_SECRET,
  REFRESH_TOKEN_LIFE,
  PRIVATE_KEY,
  SALT
}